ekf_localization:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.5
    two_d_mode: true
    publish_tf: true
    publish_acceleration: false
    print_diagnostics: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: map

    # === Use MAVROS odometry ===
    odom0: /mavros/local_position/odom
    odom0_differential: false
    odom0_relative: false
    odom0_queue_size: 10

    odom0_config: [
      true,  true,  false,   # x, y, z
      false, false, true,    # roll, pitch, yaw
      true,  true,  false,   # vx, vy, vz
      false, false, true,    # vroll, vpitch, vyaw
      false, false, false    # ax, ay, az
    ]

    # === RTABMAP RGBD ===
    odom1: /odom
    odom1_differential: false
    odom1_relative: true
    odom1_queue_size: 10
    
    odom1_config: [
      true,  true,  false,
      false, false, false,
      false, false, false,
      false, false, false,
      false, false, false
    ]

    # === DLIO lidar + imu ===
    # odom2: /dlio/odom
    # odom2_differential: false
    # odom2_relative: false
    # odom2_queue_size: 10
    #
    # odom2_config: [
    #   true,  true,  false,
    #   false, false, true,
    #   true,  true,  false,
    #   false, false, true,
    #   false, false, false
    # ]

    # === GPS ===
    # navsat0: /mavros/global_position/raw/fix
    # navsat0_queue_size: 10
    # navsat0_differential: false
    # navsat0_relative: false
    #
    # navsat0_config: [
    #   true,  true,  false,
    #   false, false, false,
    #   false, false, false,
    #   false, false, false,
    #   false, false, false
    # ]

    # === MAVROS IMU ===
    # imu0: /mavros/imu/data
    # imu0_queue_size: 20
    # imu0_differential: false
    # imu0_relative: false
    # imu0_remove_gravitational_acceleration: true
    #
    # imu0_config: [
    #   false, false, false,
    #   true,  true,  true,
    #   false, false, false,
    #   false, false, false,
    #   false, false, false
    # ]