mavros:
  ros__parameters:
    fcu_url: "tcp://127.0.0.1:5762"
    target_system_id: 1
    target_component_id: 1

    frame_id: base_link
    child_frame_id: base_link

    odom:
      publish_tf: false
      publish_tf2: false

    local_position:
      tf:
        send: false

    global_position:
      tf:
        send: false

    imu:
      frame_id: imu_link